#!/bin/bash

APPNAME=$1

source "$(dirname $0)/wv-fns"

VERSION=`get_datetime`
CONTROLFILE=`get_controlfile $APPNAME`
BR=`get_buildroot $APPNAME`

echo ">>> CREATING DEB $BR.deb"

if [ ! -f $CONTROLFILE ]; then 
    wv-create-deb-control-file $APPNAME $VERSION $CONTROLFILE
fi

dpkg-deb --build $BR
mv "$BR.deb" "$BR-$VERSION-all.deb"

echo ">>> $BR-$VERSION-all.deb WAS CREATED"