#!/bin/bash

source "$(dirname $0)/wv-fns"

APPNAME=$1

echo ">>> CREATING DEB DIRECTORY TREE FOR $APPNAME"

mkdir -p `get_debiandir $APPNAME` `get_destdir $APPNAME` `get_bindir $APPNAME`

echo ">>> DEB DIRECTORY TREE FOR $APPNAME WAS CREATED"